Repository OPENMIND-TFT/OPENMIND, pull requests merged in 2024-01, with the labels that each got.

#50 404페이지 퍼블리싱 완료 및 라우터, 글로벌 스타일 지정
  .eslintrc
  package-lock.json
  package.json
  public/assets/images/logo.png
  public/assets/images/logoWithoutBg.png
  public/assets/images/notFoundEmoji.png
  public/assets/images/paperBackground.png
  public/index.html
  src/App.js
  src/App.jsx
  src/GlobalStyle.js
  src/components/Cta/index.js
  src/components/Header/Header.js
  src/constants/constants.js
  src/pages/HomePage/index.js
  src/pages/MainPage/index.js
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
Labels: 기능 구현, 회의/세팅

#52 Feature 404,setting
  .eslintrc
  package-lock.json
  package.json
  public/assets/images/logo.png
  public/assets/images/logoWithoutBg.png
  public/assets/images/notFoundEmoji.png
  public/assets/images/paperBackground.png
  public/index.html
  src/App.js
  src/App.jsx
  src/GlobalStyle.js
  src/components/Cta/index.js
  src/components/Header/Header.js
  src/constants/constants.js
  src/pages/HomePage/index.js
  src/pages/MainPage/index.js
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
Labels: 에러 페이지, 기능 구현, 회의/세팅

#54 메인페이지 퍼블리싱
  package.json
  public/assets/images/personIcon.svg
  src/App.js
  src/GlobalStyle.js
  src/pages/HomePage/index.js
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
Labels: 메인 페이지, 퍼블리싱

#56 질문리스트 퍼블리싱, 페이지내 자체적인 기능 구현
  package-lock.json
  package.json
  public/assets/images/arrowDown.svg
  public/assets/images/arrowRight.svg
  public/assets/images/arrowUp.svg
  public/assets/images/close.svg
  public/assets/images/messages.svg
  public/index.html
  src/App.js
  src/GlobalStyle.js
  src/components/BackToMain/index.js
  src/components/BackToMain/style.js
  src/components/GoToAnswer/index.js
  src/components/GoToAnswer/style.js
  src/components/ModalQuestion/index.js
  src/components/ModalQuestion/style.js
  src/pages/List/index.js
  src/pages/List/style.js
Labels: 질문 목록 페이지, 퍼블리싱, 모달, 기능 구현

#65 질문 피드 페이지 퍼블리싱
  public/assets/images/Facebook.svg
  public/assets/images/Kakaotalk.svg
  public/assets/images/Link.svg
  public/assets/images/bucket.png
  public/assets/images/messages.svg
  public/assets/images/messagesBrown40.svg
  public/assets/images/tempProfile.svg
  public/assets/images/thumbs-down.svg
  public/assets/images/thumbs-up.svg
  public/index.html
  src/App.js
  src/pages/PheedPage/index.js
  src/pages/PheedPage/style.js
Labels: 질문 피드, 퍼블리싱, 기능 구현

#68 답변하기 페이지 퍼블리싱 #67
  public/assets/images/Link.svg
  public/assets/images/edit.svg
  public/assets/images/headerBackgroundImage.png
  public/assets/images/kebab.svg
  public/assets/images/profile.svg
  public/assets/images/thumbsDown.svg
  public/assets/images/thumbsUp.svg
  src/App.js
  src/components/Question/index.js
  src/components/Question/style.js
  src/components/QuestionHeader/index.js
  src/components/QuestionHeader/style.js
  src/components/QuestionList/index.js
  src/components/QuestionList/style.js
  src/components/ReplyPosted/index.js
  src/components/ReplyPosted/style.js
  src/pages/AnswerPage/index.js
  src/pages/AnswerPage/style.js
  src/pages/NotFoundPage/style.js
Labels: 답변하기 페이지, 퍼블리싱

#70 404페이지 리팩토링
  package.json
  src/components/Cta/index.js
  src/components/Cta/style.js
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
Labels: 리팩토링, 에러 페이지

#72 list,modal,404 반응형 완료
  .eslintrc
  package-lock.json
  package.json
  public/assets/images/Facebook.svg
  public/assets/images/Kakaotalk.svg
  public/assets/images/Link.svg
  public/assets/images/arrowDown.svg
  public/assets/images/arrowRight.svg
  public/assets/images/arrowUp.svg
  public/assets/images/bucket.png
  public/assets/images/close.svg
  public/assets/images/edit.svg
  public/assets/images/headerBackgroundImage.png
  public/assets/images/kebab.svg
  public/assets/images/logo.png
  public/assets/images/logoWithoutBg.png
  public/assets/images/messages.svg
  public/assets/images/messagesBrown40.svg
  public/assets/images/notFoundEmoji.png
  public/assets/images/paperBackground.png
  public/assets/images/personIcon.svg
  public/assets/images/profile.svg
  public/assets/images/tempProfile.svg
  public/assets/images/thumbs-down.svg
  public/assets/images/thumbs-up.svg
  public/assets/images/thumbsDown.svg
  public/assets/images/thumbsUp.svg
  public/index.html
  src/App.js
  src/App.jsx
  src/GlobalStyle.js
  src/components/BackToMain/index.js
  src/components/BackToMain/style.js
  src/components/Cta/index.js
  src/components/Cta/style.js
  src/components/GoToAnswer/index.js
  src/components/GoToAnswer/style.js
  src/components/Header/Header.js
  src/components/ModalQuestion/index.js
  src/components/ModalQuestion/style.js
  src/components/Question/index.js
  src/components/Question/style.js
  src/components/QuestionHeader/index.js
  src/components/QuestionHeader/style.js
  src/components/QuestionList/index.js
  src/components/QuestionList/style.js
  src/components/ReplyPosted/index.js
  src/components/ReplyPosted/style.js
  src/constants/constants.js
  src/pages/AnswerPage/index.js
  src/pages/AnswerPage/style.js
  src/pages/List/index.js
  src/pages/List/style.js
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
  src/pages/NotFoundPage/index.js
  src/pages/NotFoundPage/style.js
  src/pages/PheedPage/index.js
  src/pages/PheedPage/style.js
Labels: 질문 목록 페이지, 퍼블리싱, 모달, 에러 페이지

#96 메인페이지 기능구현
  package.json
  src/pages/AnswerPage/style.js
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
  src/pages/PheedPage/style.js
Labels: 메인 페이지, 기능 구현

#97 Refactor: 페이지네이션 메커니즘 변경
  package.json
  src/pages/List/index.js
  src/pages/List/style.js
Labels: 질문 목록 페이지, 리팩토링

#107 feat: 링크 버튼 클릭시 URL 복사 및 토스트 띄우기
  package.json
  src/components/CopyClipBoardButton/index.js
  src/components/CopyClipBoardButton/style.js
  src/components/Cta/index.js
  src/components/FacebookShareButton/index.js
  src/components/FacebookShareButton/style.js
  src/components/KakaoShareButton/index.js
  src/components/KakaoShareButton/style.js
  src/components/QuestionHeader/index.js
  src/components/QuestionHeader/style.js
  src/components/ShareButtonBar/index.js
  src/components/ShareButtonBar/style.js
  src/components/ToastNotification/index.js
  src/components/ToastNotification/style.js
  src/pages/NotFoundPage/index.js
Labels: 질문 피드, 답변하기 페이지, 공용 컴포넌트, 기능 구현

#108 질문페이지 무한스크롤 구현
  package-lock.json
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 기능 구현

#113 답변하기페이지 피드삭제 기능 구현
  package-lock.json
  src/api/deleteAll.js
  src/components/AnswerPageQuestionHeader/index.js
  src/components/AnswerPageQuestionHeader/style.js
  src/pages/AnswerPage/index.js
  src/pages/AnswerPage/style.js
Labels: 답변하기 페이지, 기능 구현

#116 답변하기 페이지 전체삭제(피드삭제) 기능 구현 완성
  src/api/deleteAll.js
  src/pages/AnswerPage/index.js
Labels: 답변하기 페이지, 기능 구현

#118 카드 푸터 컴포넌트화 (리액션 박스, 수정하기 버튼)
  src/api/deleteAll.js
  src/components/AnswerPageQuestionItem/index.js
  src/components/AnswerPageQuestionItem/style.js
  src/components/EditButton/index.js
  src/components/EditButton/style.js
  src/components/ReactionButtonBox/index.js
  src/components/ReactionButtonBox/style.js
  src/pages/AnswerPage/index.js
  src/pages/QuestionPage/index.js
Labels: 질문 피드, 답변하기 페이지, 공용 컴포넌트, 기능 구현

#117 feat 질문페이지 질문 삭제 기능
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 기능 구현

#120 refactor: 리액션 박스를 공통 컴포넌트로 분리
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 공용 컴포넌트, 리팩토링

#119 feat: 질문작성하기 버튼 클릭시 모달 출력
  src/components/ModalQuestion/index.js
  src/components/ModalQuestion/style.js
  src/pages/ListPage/index.js
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 모달, 기능 구현

#125 feat: 좋아요, 싫어요
  src/components/ReactionButtonBox/index.js
Labels: 질문 피드, 답변하기 페이지, 기능 구현

#128 feat: 링크공유기능 sns
  package-lock.json
  package.json
  public/_redirects
  public/assets/images/kakaoShareImage.png
  public/index.html
  src/components/FacebookShareButton/index.js
  src/components/KakaoShareButton/index.js
Labels: 질문 피드, 답변하기 페이지, 공용 컴포넌트, 기능 구현

#129 무한스크롤 커스텀훅 질문페이지 적용
  src/hooks/useInfiniteScroll.js
  src/pages/QuestionPage/index.js
Labels: 질문 피드, 커스텀 훅

#130 답변 거절 기능 구현, 케밥 로직 수정
  src/components/AnswerPageQuestionItem/index.js
  src/components/AnswerPageQuestionItem/style.js
  src/components/KebabDropDown/index.js
  src/components/KebabDropDown/style.js
Labels: 답변하기 페이지, 기능 구현

#132 답변페이지 수정버튼 기능 구현
  src/components/AnswerPageQuestionItem/index.js
  src/components/AnswerPageQuestionItem/style.js
  src/pages/AnswerPage/index.js
  src/pages/QuestionPage/index.js
Labels: 답변하기 페이지, 기능 구현

#131 메인페이지 유효성 체크 기능 구현
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
Labels: 메인 페이지, 기능 구현

#135 답변하기 페이지 케밥 기능 구현 (수정, 삭제)
  src/components/AnswerPageQuestionItem/index.js
  src/components/KebabDropDown/index.js
Labels: 답변하기 페이지, 기능 구현

#136 feat: 질문 없을시 질문 피드, 답변하기에서 not found 관련 컨텐츠 노출
  src/components/AnswerPageQuestion/index.js
  src/components/AnswerPageQuestionList/index.js
  src/components/AnswerPageQuestionList/style.js
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 답변하기 페이지, 기능 구현

#137 답변페이지 무한 스크롤 적용
  src/components/AnswerPageQuestion/index.js
  src/components/AnswerPageQuestionList/index.js
  src/pages/AnswerPage/index.js
Labels: 답변하기 페이지, 기능 구현, 커스텀 훅

#140 질문 페이지 기능 수정
  src/components/AnswerPageQuestionList/index.js
  src/components/ToastNotification/index.js
  src/components/ToastNotification/style.js
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 버그

#141 Feature 메인페이지버그픽스
  public/assets/images/thumbsDownRed50.svg
  src/components/ReactionButtonBox/style.js
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
Labels: 메인 페이지, 버그

#143 Update README.md
  README.md
Labels: 문서

#144 답변하기 페이지 기능 구현 및 버그 픽스
  public/assets/images/editBlue50.svg
  public/assets/images/rejection.svg
  public/assets/images/rejectionBlue50.svg
  public/assets/images/xIconBlue50.svg
  src/components/AnswerPageQuestion/index.js
  src/components/AnswerPageQuestionItem/index.js
  src/components/AnswerPageQuestionItem/style.js
  src/components/KebabDropDown/index.js
Labels: 답변하기 페이지, 기능 구현, 버그

#150 질문페이지, 답변페이지 공동 컴포넌트화 작업
  src/components/AnswerPageQuestionItem/index.js
  src/components/AnswerPageQuestionItem/style.js
  src/components/QuestionCardHeader/index.js
  src/components/QuestionCardHeader/style.js
  src/components/QuestionHeader/index.js
  src/components/QuestionHeader/style.js
  src/pages/AnswerPage/index.js
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 피드, 답변하기 페이지, 공용 컴포넌트

#151 메인페이지 api분리
  src/api/creatPheed.js
  src/pages/MainPage/index.js
Labels: 메인 페이지, 리팩토링

#164 api 분리 작업
  README.md
  src/api/getCardData.js
  src/api/getUserQuestionData.js
  src/components/AnswerPageQuestion/index.js
  src/pages/ListPage/index.js
  src/pages/QuestionPage/index.js
Labels: 질문 목록 페이지, 질문 피드, 답변하기 페이지, 리팩토링

#166 Feature 리스트 호버이펙트, 기능추가, 버그픽스
  src/components/AnswerPageQuestionItem/index.js
  src/components/QuestionCardHeader/style.js
  src/pages/ListPage/index.js
  src/pages/ListPage/style.js
  src/pages/QuestionPage/style.js
Labels: 질문 목록 페이지, 기능 구현, 버그, 추가기능

#168 질문 데이터 랜더링 커스텀훅 제작
  src/components/AnswerPageQuestion/index.js
  src/hooks/useGetUserQuestions.js
  src/pages/QuestionPage/index.js
Labels: 질문 피드, 답변하기 페이지, 리팩토링, 커스텀 훅

#169 답변페이지 재렌더링 기능 구현
  src/components/AnswerPageQuestion/index.js
  src/components/AnswerPageQuestionItem/index.js
  src/components/KebabDropDown/index.js
  src/hooks/useGetUserQuestions.js
Labels: 답변하기 페이지, 기능 구현

#170 Feat: 메인애니메이션 추가
  public/assets/images/gridBg.png
  public/assets/images/mainBubbleCool.png
  public/assets/images/mainBubbleHello.png
  public/assets/images/mainWithoutBg.png
  public/assets/images/paperBackground.png
  src/components/MainLineSvg/index.js
  src/components/MainLineSvg/style.js
  src/pages/MainPage/index.js
  src/pages/MainPage/style.js
Labels: 메인 페이지, 추가기능

#171 feat: 삭제버튼 클릭 시 모달창
  src/components/DeleteModal/index.js
  src/components/DeleteModal/style.js
  src/components/KebabDropDown/index.js
  src/contexts/DeleteModalContext.js
  src/contexts/QuestionIdContext.js
  src/pages/AnswerPage/index.js
  src/pages/AnswerPage/style.js
Labels: 답변하기 페이지, 모달, 추가기능

#172 데이터 호출 부분 스켈레톤 기능 구현
  package-lock.json
  package.json
  src/components/AnswerPageQuestionList/index.js
  src/components/AnswerPageQuestionList/style.js
  src/components/QuestionHeader/index.js
  src/components/QuestionHeader/style.js
  src/pages/AnswerPage/index.js
  src/pages/AnswerPage/style.js
  src/pages/ListPage/index.js
  src/pages/ListPage/style.js
  src/pages/QuestionPage/index.js
  src/pages/QuestionPage/style.js
Labels: 질문 목록 페이지, 질문 피드, 답변하기 페이지, 기능 구현, 추가기능

#174 Feature 삭제모달 리팩토링
  src/components/AnswerPageQuestionItem/style.js
  src/components/AnswerPageQuestionList/style.js
  src/components/DeleteModal/style.js
  src/components/ModalQuestion/style.js
  src/components/QuestionCardHeader/style.js
  src/pages/AnswerPage/index.js
  src/pages/QuestionPage/style.js
Labels: 리팩토링

#176 feat: 질문 피드 스켈레톤 딜레이 1초 구현
  src/hooks/useInfiniteScroll.js
  src/pages/AnswerPage/index.js
  src/pages/QuestionPage/index.js
Labels: 질문 피드, 답변하기 페이지, 기능 구현, 버그, 추가기능

#177 기타 기능 추가 (답변 삭제 재렌더링, 메타 태그 세팅)
  public/assets/images/metaLogo.png
  public/index.html
  src/components/KebabDropDown/index.js
Labels: 기능 구현, 회의/세팅, 추가기능

#180 배포 환경 정상 작동 확인 (isFirstRender useState문 제거, strict 제거)
  netlify.toml
  src/hooks/useInfiniteScroll.js
  src/index.js
Labels: 버그
